version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

formatters:
  enable:
    - gofmt
    - goimports

settings:
  errcheck:
    check-type-assertions: true
    check-blank: false

  govet:
    enable-all: true
    disable:
      - fieldalignment

  goimports:
    local-prefixes:
      - devir

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
